[versions]
agp = "9.3.2"
kotlin = "2.4.10"
activity = "1.13.0"
composeBom = "2026.08.00"
lifecycle = "2.11.0"
savedstate = "1.5.0"
junit = "4.13.2"
moonshineVoice = "0.1.5"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-savedstate = { module = "androidx.savedstate:savedstate", version.ref = "savedstate" }
junit = { module = "junit:junit", version.ref = "junit" }
moonshine-voice = { module = "ai.moonshine:moonshine-voice", version.ref = "moonshineVoice" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
